# Generated by Django 5.0.6 on 2024-08-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('password', models.CharField(max_length=16)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
