# Generated by Django 5.0.6 on 2024-08-05 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0004_users_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Plumber',
            fields=[
                ('plumber_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience', models.IntegerField()),
                ('availability', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='plumber_pics')),
                ('address', models.TextField()),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.users')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.skill')),
            ],
        ),
        migrations.CreateModel(
            name='House_Maid',
            fields=[
                ('maid_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='maid_pic')),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.users')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Home_Nurse',
            fields=[
                ('nurse_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience', models.IntegerField()),
                ('availability', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='nurse_pic')),
                ('address', models.TextField()),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.users')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Electrician',
            fields=[
                ('electrician_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience', models.IntegerField()),
                ('availability', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='electrician_pics')),
                ('address', models.TextField()),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.users')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Carpenter',
            fields=[
                ('carpenter_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience', models.IntegerField()),
                ('availability', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='carpenter_pic')),
                ('address', models.TextField()),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.users')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.skill')),
            ],
        ),
    ]
