# Generated by Django 5.0.6 on 2024-08-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0005_skill_plumber_house_maid_home_nurse_electrician_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house_maid',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='user',
            new_name='user_id',
        ),
    ]
