# Generated by Django 5.0.6 on 2024-08-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0007_carpenter_place_electrician_place_home_nurse_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpenter',
            name='district',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='electrician',
            name='district',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='home_nurse',
            name='district',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='house_maid',
            name='district',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='plumber',
            name='district',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='district',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='place',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
