# Generated by Django 5.0.6 on 2024-08-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0010_alter_booking_customer_alter_booking_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='worker',
            new_name='worker_id',
        ),
    ]
