# Generated by Django 5.0.6 on 2024-08-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0011_rename_customer_booking_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carpenter',
            name='availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='electrician',
            name='availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='home_nurse',
            name='availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house_maid',
            name='availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plumber',
            name='availability',
            field=models.IntegerField(default=0),
        ),
    ]
