# Generated by Django 5.0.6 on 2024-08-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0012_users_availability_alter_carpenter_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
