# Generated by Django 5.0.6 on 2024-08-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0013_alter_users_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpenter',
            old_name='usertype',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='electrician',
            old_name='usertype',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='home_nurse',
            old_name='usertype',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='plumber',
            old_name='usertype',
            new_name='user_id',
        ),
    ]
