# Generated by Django 5.0.6 on 2024-08-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0014_rename_usertype_carpenter_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house_maid',
            old_name='skill',
            new_name='skill_id',
        ),
    ]
