# Generated by Django 5.0.6 on 2024-08-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0018_conversation_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='participants',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
