# Generated by Django 5.0.6 on 2024-08-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0019_remove_conversation_participants_delete_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('house_maid', 'House Maid'), ('nurse', 'Home Nurse'), ('plumber', 'Plumber'), ('carpenter', 'Carpenter'), ('electrician', 'Electrician')], max_length=20, unique=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='hours_booked',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='pay_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
