# Generated by Django 5.0.6 on 2024-08-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0022_alter_chatmessage_receiver_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
    ]
