# Generated by Django 5.0.6 on 2024-08-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0023_remove_chatmessage_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
