# Generated by Django 5.0.6 on 2024-08-30 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0024_users_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('usertype', 'admin')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='Home_app.users'),
        ),
    ]
