# Generated by Django 5.0.6 on 2024-09-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0026_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
