# Generated by Django 5.0.6 on 2024-09-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0027_alter_payments_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
