# Generated by Django 5.0.6 on 2024-09-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0028_alter_payments_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
